/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamPracticeRouteImport } from './routes/exam-practice'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as GrammarSetIdRouteImport } from './routes/grammar.$setId'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryFolderIdRouteImport } from './routes/library.$folderId'
import { Route as SetsSetIdRouteImport } from './routes/sets.$setId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPracticeRoute = ExamPracticeRouteImport.update({
  id: '/exam-practice',
  path: '/exam-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarSetIdRoute = GrammarSetIdRouteImport.update({
  id: '/grammar/$setId',
  path: '/grammar/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryFolderIdRoute = LibraryFolderIdRouteImport.update({
  id: '/library/$folderId',
  path: '/library/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdRoute = SetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/groups': typeof GroupsIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/sets/$setId'
    | '/groups/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/sets/$setId'
    | '/groups'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/sets/$setId'
    | '/groups/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamPracticeRoute: typeof ExamPracticeRoute
  LessonsRoute: typeof LessonsRoute
  MockTestRoute: typeof MockTestRoute
  RoadmapRoute: typeof RoadmapRoute
  ScanRoute: typeof ScanRoute
  TrashRoute: typeof TrashRoute
  GrammarSetIdRoute: typeof GrammarSetIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  LibraryFolderIdRoute: typeof LibraryFolderIdRoute
  SetsSetIdRoute: typeof SetsSetIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-practice': {
      id: '/exam-practice'
      path: '/exam-practice'
      fullPath: '/exam-practice'
      preLoaderRoute: typeof ExamPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/$setId': {
      id: '/grammar/$setId'
      path: '/grammar/$setId'
      fullPath: '/grammar/$setId'
      preLoaderRoute: typeof GrammarSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$folderId': {
      id: '/library/$folderId'
      path: '/library/$folderId'
      fullPath: '/library/$folderId'
      preLoaderRoute: typeof LibraryFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId': {
      id: '/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof SetsSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamPracticeRoute: ExamPracticeRoute,
  LessonsRoute: LessonsRoute,
  MockTestRoute: MockTestRoute,
  RoadmapRoute: RoadmapRoute,
  ScanRoute: ScanRoute,
  TrashRoute: TrashRoute,
  GrammarSetIdRoute: GrammarSetIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  LibraryFolderIdRoute: LibraryFolderIdRoute,
  SetsSetIdRoute: SetsSetIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
