/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamPracticeRouteImport } from './routes/exam-practice'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as GrammarSetIdRouteImport } from './routes/grammar.$setId'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryFolderIdRouteImport } from './routes/library.$folderId'
import { Route as RoadmapRoadmapIdRouteImport } from './routes/roadmap_.$roadmapId'
import { Route as SetsSetIdRouteImport } from './routes/sets.$setId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherFoldersRouteImport } from './routes/teacher.folders'
import { Route as TeacherLessonsRouteImport } from './routes/teacher.lessons'
import { Route as TeacherTrashRouteImport } from './routes/teacher.trash'
import { Route as GrammarSetIdTestRouteImport } from './routes/grammar_.$setId.test'
import { Route as TeacherExamsIndexRouteImport } from './routes/teacher.exams.index'
import { Route as TeacherExamsExamIdRouteImport } from './routes/teacher.exams.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPracticeRoute = ExamPracticeRouteImport.update({
  id: '/exam-practice',
  path: '/exam-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarSetIdRoute = GrammarSetIdRouteImport.update({
  id: '/grammar/$setId',
  path: '/grammar/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryFolderIdRoute = LibraryFolderIdRouteImport.update({
  id: '/library/$folderId',
  path: '/library/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoadmapIdRoute = RoadmapRoadmapIdRouteImport.update({
  id: '/roadmap_/$roadmapId',
  path: '/roadmap/$roadmapId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdRoute = SetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/teacher/classes',
  path: '/teacher/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherFoldersRoute = TeacherFoldersRouteImport.update({
  id: '/teacher/folders',
  path: '/teacher/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/teacher/lessons',
  path: '/teacher/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTrashRoute = TeacherTrashRouteImport.update({
  id: '/teacher/trash',
  path: '/teacher/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarSetIdTestRoute = GrammarSetIdTestRouteImport.update({
  id: '/grammar_/$setId/test',
  path: '/grammar/$setId/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamsIndexRoute = TeacherExamsIndexRouteImport.update({
  id: '/teacher/exams/',
  path: '/teacher/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamsExamIdRoute = TeacherExamsExamIdRouteImport.update({
  id: '/teacher/exams/$examId',
  path: '/teacher/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/roadmap/$roadmapId': typeof RoadmapRoadmapIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/folders': typeof TeacherFoldersRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/trash': typeof TeacherTrashRoute
  '/groups/': typeof GroupsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/grammar/$setId/test': typeof GrammarSetIdTestRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/exams/': typeof TeacherExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/roadmap/$roadmapId': typeof RoadmapRoadmapIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/folders': typeof TeacherFoldersRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/trash': typeof TeacherTrashRoute
  '/groups': typeof GroupsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/grammar/$setId/test': typeof GrammarSetIdTestRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/exams': typeof TeacherExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam-practice': typeof ExamPracticeRoute
  '/lessons': typeof LessonsRoute
  '/mock-test': typeof MockTestRoute
  '/roadmap': typeof RoadmapRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
  '/grammar/$setId': typeof GrammarSetIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/library/$folderId': typeof LibraryFolderIdRoute
  '/roadmap_/$roadmapId': typeof RoadmapRoadmapIdRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/folders': typeof TeacherFoldersRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/trash': typeof TeacherTrashRoute
  '/groups/': typeof GroupsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/grammar_/$setId/test': typeof GrammarSetIdTestRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/exams/': typeof TeacherExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/roadmap/$roadmapId'
    | '/sets/$setId'
    | '/teacher/classes'
    | '/teacher/folders'
    | '/teacher/lessons'
    | '/teacher/trash'
    | '/groups/'
    | '/library/'
    | '/teacher/'
    | '/grammar/$setId/test'
    | '/teacher/exams/$examId'
    | '/teacher/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/roadmap/$roadmapId'
    | '/sets/$setId'
    | '/teacher/classes'
    | '/teacher/folders'
    | '/teacher/lessons'
    | '/teacher/trash'
    | '/groups'
    | '/library'
    | '/teacher'
    | '/grammar/$setId/test'
    | '/teacher/exams/$examId'
    | '/teacher/exams'
  id:
    | '__root__'
    | '/'
    | '/exam-practice'
    | '/lessons'
    | '/mock-test'
    | '/roadmap'
    | '/scan'
    | '/trash'
    | '/grammar/$setId'
    | '/groups/$groupId'
    | '/library/$folderId'
    | '/roadmap_/$roadmapId'
    | '/sets/$setId'
    | '/teacher/classes'
    | '/teacher/folders'
    | '/teacher/lessons'
    | '/teacher/trash'
    | '/groups/'
    | '/library/'
    | '/teacher/'
    | '/grammar_/$setId/test'
    | '/teacher/exams/$examId'
    | '/teacher/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamPracticeRoute: typeof ExamPracticeRoute
  LessonsRoute: typeof LessonsRoute
  MockTestRoute: typeof MockTestRoute
  RoadmapRoute: typeof RoadmapRoute
  ScanRoute: typeof ScanRoute
  TrashRoute: typeof TrashRoute
  GrammarSetIdRoute: typeof GrammarSetIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  LibraryFolderIdRoute: typeof LibraryFolderIdRoute
  RoadmapRoadmapIdRoute: typeof RoadmapRoadmapIdRoute
  SetsSetIdRoute: typeof SetsSetIdRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherFoldersRoute: typeof TeacherFoldersRoute
  TeacherLessonsRoute: typeof TeacherLessonsRoute
  TeacherTrashRoute: typeof TeacherTrashRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  GrammarSetIdTestRoute: typeof GrammarSetIdTestRoute
  TeacherExamsExamIdRoute: typeof TeacherExamsExamIdRoute
  TeacherExamsIndexRoute: typeof TeacherExamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-practice': {
      id: '/exam-practice'
      path: '/exam-practice'
      fullPath: '/exam-practice'
      preLoaderRoute: typeof ExamPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/$setId': {
      id: '/grammar/$setId'
      path: '/grammar/$setId'
      fullPath: '/grammar/$setId'
      preLoaderRoute: typeof GrammarSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$folderId': {
      id: '/library/$folderId'
      path: '/library/$folderId'
      fullPath: '/library/$folderId'
      preLoaderRoute: typeof LibraryFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap_/$roadmapId': {
      id: '/roadmap_/$roadmapId'
      path: '/roadmap/$roadmapId'
      fullPath: '/roadmap/$roadmapId'
      preLoaderRoute: typeof RoadmapRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId': {
      id: '/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof SetsSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/teacher/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/folders': {
      id: '/teacher/folders'
      path: '/teacher/folders'
      fullPath: '/teacher/folders'
      preLoaderRoute: typeof TeacherFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/teacher/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/trash': {
      id: '/teacher/trash'
      path: '/teacher/trash'
      fullPath: '/teacher/trash'
      preLoaderRoute: typeof TeacherTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar_/$setId/test': {
      id: '/grammar_/$setId/test'
      path: '/grammar/$setId/test'
      fullPath: '/grammar/$setId/test'
      preLoaderRoute: typeof GrammarSetIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exams/': {
      id: '/teacher/exams/'
      path: '/teacher/exams'
      fullPath: '/teacher/exams/'
      preLoaderRoute: typeof TeacherExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exams/$examId': {
      id: '/teacher/exams/$examId'
      path: '/teacher/exams/$examId'
      fullPath: '/teacher/exams/$examId'
      preLoaderRoute: typeof TeacherExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamPracticeRoute: ExamPracticeRoute,
  LessonsRoute: LessonsRoute,
  MockTestRoute: MockTestRoute,
  RoadmapRoute: RoadmapRoute,
  ScanRoute: ScanRoute,
  TrashRoute: TrashRoute,
  GrammarSetIdRoute: GrammarSetIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  LibraryFolderIdRoute: LibraryFolderIdRoute,
  RoadmapRoadmapIdRoute: RoadmapRoadmapIdRoute,
  SetsSetIdRoute: SetsSetIdRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherFoldersRoute: TeacherFoldersRoute,
  TeacherLessonsRoute: TeacherLessonsRoute,
  TeacherTrashRoute: TeacherTrashRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  GrammarSetIdTestRoute: GrammarSetIdTestRoute,
  TeacherExamsExamIdRoute: TeacherExamsExamIdRoute,
  TeacherExamsIndexRoute: TeacherExamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
